### ISSUE TITLE
Loadworkbook, readWorksheet, readWorksheet not found

### ISSUE THREAD

**Issue by chamdan0150** [miraisolutions/xlconnect#100]
Hi,
I did install XLConnect and XLConnectJars and have java 64bits installed and when I try the following:
# Load the workbook
 Eventsfile <- system.file("C:/Users/Hussein/Documents/Events.xlsx", package = "XLConnect")
wb = loadWorkbook(Eventsfile)
 
# Read the data on the sheet named "data"
data = readWorksheet(wb, sheet = "data")
# Note all the NA values due to the cells with text containing
# 'some stuff'
print(head(data))
 
# Let's assume we only roughly know the data is located within some
# given boundaries (exact location would be startRow = 1,
# startCol = 1, endRow = 101, endCol = 5)
data = readWorksheet(wb, sheet = "data", startRow = 1, startCol = 1,
                     endRow = 101, endCol = 5)
# However, XLConnect is capable to find the actual data region
print(head(data))

I get the following error message:

> # Load the workbook
>  Eventsfile <- system.file("C:/Users/Hussein/Documents/Events.xlsx", package = "XLConnect")
> wb = loadWorkbook(Eventsfile)
Error in loadWorkbook(Eventsfile) : 
  could not find function "loadWorkbook"
>  
> # Read the data on the sheet named "data"
> data = readWorksheet(wb, sheet = "data")
Error in readWorksheet(wb, sheet = "data") : 
  could not find function "readWorksheet"
> # Note all the NA values due to the cells with text containing
> # 'some stuff'
> print(head(data))
                                                                            
1 function (..., list = character(), package = NULL, lib.loc = NULL,        
2     verbose = getOption("verbose"), envir = .GlobalEnv, overwrite = TRUE) 
3 {                                                                         
4     fileExt <- function(x) {                                              
5         db <- grepl("\\\\.[^.]+\\\\.(gz|bz2|xz)$", x)                     
6         ans <- sub(".*\\\\.", "", x)                                      
>  
> # Let's assume we only roughly know the data is located within some
> # given boundaries (exact location would be startRow = 1,
> # startCol = 1, endRow = 101, endCol = 5)
> data = readWorksheet(wb, sheet = "data", startRow = 1, startCol = 1,
+                      endRow = 101, endCol = 5)
Error in readWorksheet(wb, sheet = "data", startRow = 1, startCol = 1,  : 
  could not find function "readWorksheet"
> # However, XLConnect is capable to find the actual data region
> print (head(data))

**Comment by chamdan0150** [comment]
I found out that Openxlsx, xlsx, readxl was needed in order for loadWorkbook to be available and same for the other.
So consider this issue closed.

**Comment by chamdan0150** [comment]
Issue resolved!

**Comment by spoltier** [comment]
Hi @chamdan0150 - you shouldn't need these dependencies for this to work. Did you make sure to load XLConnect before attempting these commands ? Even after installing, `library(XLConnect)` is still required to load the package.

**Comment by chamdan0150** [comment]
Thanks spoltier,
