### ISSUE TITLE
Switch to travis-ci.com

### ISSUE THREAD

**Issue by riccardoporreca** [miraisolutions/xlconnect#105]
With the support to open source repositories, travis-ci.com is now recommended over travis-ci.org (https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps)

- [ ] Migrate the repository at https://travis-ci.com/organizations/miraisolutions/migrate
- [ ] Update the Travis CI badge

**Comment by spoltier** [comment]
As discussed, will try to move to GH actions directly.

**Comment by spoltier** [comment]
Moved to GH actions in #116
