### ISSUE TITLE
Question on Java Required version

### ISSUE THREAD

**Issue by AllanRTate** [miraisolutions/xlconnect#109]
Hello, 
I'm relatively new to R and am trying to use it with Excel files. I'm using:
 
RStudio v. 1.3.1056
R version 4.0.2
java version "14.0.2" 2020-07-14

I successfully installed XLConnect, but loading the package failed with this error:

error: Installed java version 14.0.2+12-46 is not between Java>=8 and <=11! This is needed for this package

Questions:
1. Where are system requirements detailed? The user manual only said jre v6 or higher.
2. Is support for java v. 14 coming and if so when?
3. Besides downgrading to java v. 11, is there another option to solve this?
4. Is there an alternative to XLConnect?

Thanks,

Allan

**Comment by spoltier** [comment]
Hi @AllanRTate,

We'll likely include support for later java versions at some point in the future. Don't have a timeline for that unfortunately. 
In general, you should use CRAN to install and see requirements of R packages. See for XLConnect: https://cran.r-project.org/package=XLConnect.
Unfortunately, there is no other way but to downgrade to java 11.
Depending on what you're looking for, there are some alternatives, e.g. [xlsx](https://cran.r-project.org/package=xlsx).

**Comment by CidaJiang** [comment]
Dear Spoltier,

This is a new user of the XLConnect.package. 
Same to AllenRTate, I also have the question that require(XLConnect) failed, as following:

"_Error: package or namespace load failed for ‘XLConnect’:
 .onLoad failed in loadNamespace() for 'XLConnect', details:
  call: fun(libname, pkgname)
  error: Installed java version 15.0.1+9-18 is not between Java>=8 and <=11! This is needed for this package"_

I spent two whole days to solve the problem, but failed.
I don't know why I get the error.

I'm using:

_macOS Catalina 10.15.7

R version 4.0.3 (2020-10-10) (64-bit)

java version "15.0.1" 2020-10-20
Java(TM) SE Runtime Environment (build 15.0.1+9-18)
Java HotSpot(TM) 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing)_

In addition, I require(rJava) successfully in R. 

What should I do to require(XLConnect) successfully?

Thanks.

Cida
