### ISSUE TITLE
Getting extra x in my variable names

### ISSUE THREAD

**Issue by Dacorogna** [miraisolutions/xlconnect#111]
When I write in an excel spreadsheet I get lots of extra x instead of simply the name of my variables. How can I get rid of this.

Here is an example of what I get

x | Param_g_exp_gpd.Infos
-- | --
used_model | g_exp_gpd
x | 0.8
Alpha | 0.8
x | 1e-05
Rho | 1000
x |  
Epsilon |  
x |  
Max_iter |

**Comment by Dacorogna** [comment]
The code used for this was:
yinfo<-data.frame(Param_g_exp_gpd$Infos)
  writeWorksheet(exc,yinfo,sheet = "Results", startRow = row, startCol = col)

**Comment by spoltier** [comment]
This does not usually occur with a dataframe. What is the value of `yinfo` ? You may use the `rownames` parameter in `writeWorksheet` to specify the column to use for row names.

**Comment by Dacorogna** [comment]
Thank you, Simon, I wanted to run my program to show you the problem, but another problem appeared. I cannot load XLConnect anymore. I get this message:

Error: package or namespace load failed for ‘XLConnect’:

.onLoad failed in loadNamespace() for 'rJava', details:

  call: fun(libname, pkgname)

  error: JAVA_HOME cannot be determined from the Registry

> 

Although I have installed rJava.

 

Best regards, Michel

**Comment by spoltier** [comment]
Hi @Dacorogna, this error is produced by rJava; rJava is not able to detect Java on your system. You might need to reinstall Java.

**Comment by Dacorogna** [comment]
Thank you Simon for your patience. I just did it but I get now another error now:

 

Error: package or namespace load failed for ‘XLConnect’:

.onLoad failed in loadNamespace() for 'XLConnect', details:

  call: system2("cat", c("/etc/*-release"), stdout = TRUE, stderr = TRUE)

  error: '"cat"' not found

 

Best regards,

 

Michel Dacorogna

**Comment by spoltier** [comment]
@Dacorogna - see #132 - we are working on this problem, there's some workarounds mentioned in the ticket.

**Comment by Dacorogna** [comment]
Hello Simon,

I tried to install the package with what you recommended in another post:
install.packages("XLConnect", type="source",INSTALL_opts=c("--no-multiarch"))

But it did not work. It gave the same error message.

**Comment by Dacorogna** [comment]
I am sorry I pushed the wrong button. Of course, it is not closed

**Comment by spoltier** [comment]
@Dacorogna did you remove XLConnect before trying to install it again (`remove.packages`) ? I recommend trying to install the pre-release package I referenced in [this comment](https://github.com/miraisolutions/xlconnect/issues/132#issuecomment-829434823), otherwise you will need to install RTools for windows.

**Comment by Dacorogna** [comment]
Dear Simon,

 

I have not succeeded to install your beta version and make it work in my environment. I hope you will soon release a new version that I could use.

 

Best regards,

 

Michel

**Comment by spoltier** [comment]
@Dacorogna we have released 1.0.4 which should fix the problem.
