### ISSUE TITLE
Question about require(XLConnect) failed

### ISSUE THREAD

**Issue by CidaJiang** [miraisolutions/xlconnect#112]
Dear Spoltier,

This is a new user of the XLConnect.package.
Same to AllenRTate, I also have the question that require(XLConnect) failed, as following:

"Error: package or namespace load failed for ‘XLConnect’:
.onLoad failed in loadNamespace() for 'XLConnect', details:
call: fun(libname, pkgname)
error: Installed java version 15.0.1+9-18 is not between Java>=8 and <=11! This is needed for this package"

I spent two whole days to solve the problem, but failed.
I don't know why I get the error.

I'm using:

_macOS Catalina 10.15.7

R version 4.0.3 (2020-10-10) (64-bit)

java version "15.0.1" 2020-10-20
Java(TM) SE Runtime Environment (build 15.0.1+9-18)
Java HotSpot(TM) 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing)_

In addition, I require(rJava) successfully in R.

What should I do to require(XLConnect) successfully?

Thanks.

Cida

**Comment by CidaJiang** [comment]
I have degraded Java version 15.0.1+9-18 to Java version 11.
Then I require(XLConnect) successfully in R.

**Comment by spoltier** [comment]
Hi @CidaJiang, as you've noticed this is linked to issue #109. I'm working on adding support for newer versions of Java.
