### ISSUE TITLE
XLConnect picking up wrong Java version

### ISSUE THREAD

**Issue by richardreeve** [miraisolutions/xlconnect#114]
I am running R on MacOS 10.15.7 and I have java versions 11 and 15 installed. I use `jenv` to choose version 11 as the active version, and running `R CMD javareconf` correctly picks up this version. I can also install the `rJava` package, and it also picks up the correct java version. However, when I attempt to install `XLConnect` it does not use the system configured version through jenv, which both javareconf and rJava pick up, but instead calls `/usr/libexec/java_home` directly, which apparently by default returns the latest version of java irrespective of other configurations.

Could `XLConnect` be fixed so it picks up the correct version of java, as javareconf and rJava do?

Edited to add: if I uninstall version 15, then XLConnect installs correctly, but it is still only using the R system default Java version by accident.

**Comment by spoltier** [comment]
hi @richardreeve - thank you for reporting this issue.
The described behavior is quite strange. Unfortunately I don't currently have access to a macOS machine to try and reproduce it. _XLConnect_ uses _rJava_ to call java functionality, so it should rely on the same java version.
Could you try to load and initialize _rJava_ with java version 11 selected via `jenv`, then run the following in the R session:
```r
.jcall("java/lang/System", "S", "getProperty", "java.runtime.version")
```
and report the output.

**Comment by hsmith9002** [comment]
I ran into this issue too.I don't think the problem is with XLConnect, but with the R environment loading the right java version. The way I got around it was to create an R Project, and open it using this shell script (assuming you have java 8 installed on your machine).

`# start_R_with_Java_8.sh --
#!/bin/bash

export JAVA_HOME=/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home
export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
export PATH=$JAVA_HOME/bin:${PATH}
open Customer_Journey.Rproj`

**Comment by spoltier** [comment]
@richardreeve @hsmith9002 the java detection implementation changed in the latest released version (1.0.2), would appreciate feedback if you notice something changed. Specifically it now does a command line call to `java` to check the version.

**Comment by spoltier** [comment]
@richardreeve @hsmith9002 we have made some additional improvements and increased the maximum java version to 16. I'm closing this ticket now as I haven't heard back.

**Comment by richardreeve** [comment]
Sorry - somehow I didn't notice these messages in the stream of github notifications I had at the time. You have fixed this - thanks so much!

**Comment by spoltier** [comment]
@richardreeve  Thank you for getting back to me, glad to hear your issue is fixed!
