### ISSUE TITLE
XLConnect generates corrupt files that can't be re-written

### ISSUE THREAD

**Issue by hsmith9002** [miraisolutions/xlconnect#118]
Hello,

I am using XLConnect to update data in an .xlsx (2019), and the first time a write to the file everything works swimmingly, but then if I write to that same file again, it becomes corrupted and won't open?

Thank you
Harry

**Comment by spoltier** [comment]
Hi Harry

Can you reproduce this issue with version 1.0.2 recently published on CRAN, and could you provide the code where this occurs?

Thanks
Simon

**Comment by spoltier** [comment]
Can't reproduce (covered by unit tests)
