### ISSUE TITLE
Error with loadWorkbook

### ISSUE THREAD

**Issue by assaforon** [miraisolutions/xlconnect#123]
Hi,

Longtime XLConnect user here. In fact, my table1xls package relies on it heavily.

Having upgraded to 4.0.4 and 1.0.2, I'm getting this:

“Error: NoClassDefFoundError (Java): org/apache/poi/openxml4j/exceptions/InvalidFormatException"

I just double-checked with 4.0.2 and 1.0.1, and that still works as designated.

I use a windows 10 laptop with 64-bit offline java and 64-bit R.

Thanks,
Assaf

**Comment by spoltier** [comment]
Hi @assaforon, thanks for reporting.
Do you have an Excel workbook you can share to reproduce this issue ?
Please also mention the java version you're using.

**Comment by assaforon** [comment]
Hi @spoltier , 
This is not related to a specific workbook. I'm getting this error when trying to open any workbook.
I have 64-bit Java 8 update 281.

Thanks, Assaf

**Comment by spoltier** [comment]
Hi @assaforon, we have released a new version. We were not able to reproduce your issue, so we don't know if it was fixed. You may want to try upgrading however.

**Comment by spoltier** [comment]
@assaforon please open a ticket with more information if the issue has not been solved.

**Comment by vk111** [comment]
Hi, I have the same problem

my versions are:

R:
               _                                
platform       x86_64-w64-mingw32               
arch           x86_64                           
os             mingw32                          
crt            ucrt                             
system         x86_64, mingw32                  
status                                          
major          4                                
minor          2.1                              
year           2022                             
month          06                               
day            23                               
svn rev        82513                            
language       R                                
version.string R version 4.2.1 (2022-06-23 ucrt)

Java:
8.0.2710.9
