### ISSUE TITLE
onLoad error if user doesn't have write permission

### ISSUE THREAD

**Issue by marciz** [miraisolutions/xlconnect#124]
https://github.com/miraisolutions/xlconnect/blob/0023b0c27f6d981487c4aa563470ef74df6fb391/R/onLoad.R#L79

**Comment by spoltier** [comment]
This message means there was a previous error during the onLoad, can you provide as much output as possible when calling `library("XLConnect")` ?

**Comment by marciz** [comment]
`library(XLConnect)`

> Error: package or namespace load failed for ‘XLConnect’:
>  .onLoad failed in loadNamespace() for 'XLConnect', details:
>   call: file(file, ifelse(append, "a", "w"))
>   error: cannot open the connection

`file.exists(paste(.libPaths(), "XLConnect", ".fail", sep = "/"))`

> FALSE FALSE

Behind proxy for onLoad repo
`RCurl::url.exists("https://repo1.maven.org/maven2"`)

> FALSE

`sessionInfo()`

> R version 3.6.1 (2019-07-05)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows Server 2008 R2 x64 (build 7601) Service Pack 1
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=Latvian_Latvia.1257  LC_CTYPE=Latvian_Latvia.1257   
> [3] LC_MONETARY=Latvian_Latvia.1257 LC_NUMERIC=C                   
> [5] LC_TIME=Latvian_Latvia.1257    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> loaded via a namespace (and not attached):
> [1] compiler_3.6.1 tools_3.6.1    rJava_0.9-11

**Comment by spoltier** [comment]
Thanks for the feedback @marciz. We need to avoid writing the file in the interactive case, when the package has already been installed.

**Comment by spoltier** [comment]
Should be fixed in version 1.0.3 with fix for #122 (It is still affected by #132 however).
