### ISSUE TITLE
Error loading XLConnect (loadNamespace error, argument is of length zero)

### ISSUE THREAD

**Issue by FelipeCotia** [miraisolutions/xlconnect#125]
When trying:

library(XLConnect)

I get the error message:

Error: package or namespace load failed for ‘XLConnect’:
.onLoad failed in loadNamespace() for 'XLConnect', details:
call: if (twoFirst == "1.") {
error: argument is of length zero

Running R version 4.0.3 (2020-10-10), RStudio Version 1.4.1103 and Java SE Development Kit 16 on Windows 10 x64.

**Comment by spoltier** [comment]
Hi, we do not support java 16 yet.

**Comment by FelipeCotia** [comment]
Thank you for answer.

I downgrade the Java version and tried 8 and 11 versions. This time the error changed:

XLConnect: It seems downloading the JAR dependencies may have failed. If you would like to use a different maven repository, please set the environment variable XLCONNECT_JAVA_REPO_URL to a valid URL, e.g. Sys.setenv(XLCONNECT_JAVA_REPO_URL='https://jcenter.bintray.com'), and reinstall the package.
XLConnect 1.0.2 by Mirai Solutions GmbH [aut],
Martin Studer [cre],
The Apache Software Foundation [ctb, cph] (Apache POI),
Graph Builder [ctb, cph] (Curvesapi Java library)
https://mirai-solutions.ch
https://github.com/miraisolutions/xlconnect

Setting XLCONNECT_JAVA_REPO_URL to a valid url didn't work with me but I realize some curious: if a detach rJava package and  load this again, finally I can load and use XLConnect, even with Java version 16.

**Comment by FelipeCotia** [comment]
> Hi, we do not support java 16 yet. Looks like parsing the java version no longer works with java 16. will look into improving that.

Thank you for answer.

I downgrade the Java version and tried 8 and 11 versions. This time the error changed:

XLConnect: It seems downloading the JAR dependencies may have failed. If you would like to use a different maven repository, please set the environment variable XLCONNECT_JAVA_REPO_URL to a valid URL, e.g. Sys.setenv(XLCONNECT_JAVA_REPO_URL='https://jcenter.bintray.com'), and reinstall the package.
XLConnect 1.0.2 by Mirai Solutions GmbH [aut],
Martin Studer [cre],
The Apache Software Foundation [ctb, cph] (Apache POI),
Graph Builder [ctb, cph] (Curvesapi Java library)
https://mirai-solutions.ch
https://github.com/miraisolutions/xlconnect

Setting XLCONNECT_JAVA_REPO_URL to a valid url didn't work with me but I realize some curious: if a detach rJava package and load this again, finally I can load and use XLConnect, even with Java version 16.

**Comment by luivalcab** [comment]
Good evening! One of my students was experiencing exactly the same problem mentioned above (in our case, with R version 4.0.3 in Windows 10, Java 1.8) and no solution was working for him. However, a few minutes ago, exploring his environment variables, we noticed that he had environment variable _JAVA_OPTIONS set to -Xmx512m. Once we have removed such variable, XLConnect is working properly.

**Comment by FelipeCotia** [comment]
> Good evening! One of my students was experiencing exactly the same problem mentioned above (in our case, with R version 4.0.3 in Windows 10, Java 1.8) and no solution was working for him. However, a few minutes ago, exploring his environment variables, we noticed that he had environment variable _JAVA_OPTIONS set to -Xmx512m. Once we have removed such variable, XLConnect is working properly.

Good afternoon! Thanks for help but here I don't have this variable in environment. I looked fo other suspicious variables but I did not find it.

**Comment by spoltier** [comment]
@FelipeCotia looks like you ran into #122 - Looks like it always happens on Windows. Indeed it shouldn't affect the normal function of the package.
@luivalcab as I mention above this error will always occur on Windows, but the package should still work. Insufficient memory allocated to Java may cause some other issues though.

**Comment by luivalcab** [comment]
Thank you for your answer @spoltier,  in our case that setting of the _JAVA_OPTIONS variable to -Xmx512m raised the error informed at the beginning of this thread, once removed everything worked fine, I wanted to share my experience just in case it could be useful for other users.

**Comment by FelipeCotia** [comment]
> @FelipeCotia looks like you ran into #122 - Looks like it always happens on Windows. Indeed it shouldn't affect the normal function of the package.
> @luivalcab as I mention above this error will always occur on Windows, but the package should still work. Insufficient memory allocated to Java may cause some other issues though.

@spoltier thanks for help. Yes, now I in #122 but setting the environment variable did not work to me. But how i tell above detaching rJava and loading it again works at the end and I still using XLConnect. For me it's OK.
Thanks again.

**Comment by brzaz228** [comment]
> > Good evening! One of my students was experiencing exactly the same problem mentioned above (in our case, with R version 4.0.3 in Windows 10, Java 1.8) and no solution was working for him. However, a few minutes ago, exploring his environment variables, we noticed that he had environment variable _JAVA_OPTIONS set to -Xmx512m. Once we have removed such variable, XLConnect is working properly.
> 
> Good afternoon! Thanks for help but here I don't have this variable in environment. I looked fo other suspicious variables but I did not find it.

@luivalcab  how do you check for this variable? is this in Rstudio or somewhere else?

**Comment by spoltier** [comment]
@brzaz228 you can check environment variables in R with `Sys.getenv("_JAVA_OPTIONS")`. @FelipeCotia closing this issue as we have improved the java version check, and increased the maximum java version to 16.
