### ISSUE TITLE
Review cloudbuild config / script

### ISSUE THREAD

**Issue by spoltier** [miraisolutions/xlconnect#130]
The files cloudbuild.yaml and cloudcheck.sh are likely out of date (notably references to XLConnectJars in cloudcheck.sh).
* check if still needed / used
* clean up / update

**Comment by spoltier** [comment]
Disabled the cloud build trigger in google cloud console.

**Comment by RolandASc** [comment]
GitHub actions allows us sufficient testing of various OS and Java versions
