### ISSUE TITLE
	Reading sheet "xyz" ...Error: NoClassDefFoundError (Java): com/zaxxer/sparsebits/SparseBitSet

### ISSUE THREAD

**Issue by hmamaysky** [miraisolutions/xlconnect#131]
When reading in a tab from a particular Excel spreadsheet, I would get the following  error:

	Reading sheet "HISTORICAL BONDS" ...Error: NoClassDefFoundError (Java): com/zaxxer/sparsebits/SparseBitSet

When I downloaded SparseBitSet-1.2.jar and added it to the .../library/XLConnect/java directory, everything worked fine.  Should this jar file be included with the package distribution?  I am running on Windows 10.

**Comment by merangelik** [comment]
@hmamaysky thank you for your comment, it solved the problems I've been having recently rendering the same error message you got.

**Comment by spoltier** [comment]
Hi @hmamaysky / @merangelik, it would be useful to have an example Excel spreadsheet that produces this error, as our tests do not cover it.

**Comment by hmamaysky** [comment]
The attached file causes the error.  The command sequence is below.   But adding SparseBitSet-1.2.jar to the XLConnect/java/ directory fixes the issue.

[test_xlconnect.xlsx](https://github.com/miraisolutions/xlconnect/files/6612682/test_xlconnect.xlsx)

```
> require(XLConnect)
Loading required package: XLConnect
XLConnect 1.0.3 by Mirai Solutions GmbH [aut],
  Martin Studer [cre],
  The Apache Software Foundation [ctb, cph] (Apache POI),
  Graph Builder [ctb, cph] (Curvesapi Java library)
https://mirai-solutions.ch
https://github.com/miraisolutions/xlconnect
> wb <- loadWorkbook('c:/temp/test_xlconnect.xlsx')
> sh <- readWorksheet(wb,'hist')
Error: NoClassDefFoundError (Java): com/zaxxer/sparsebits/SparseBitSet
```

**Comment by andreas50** [comment]
I am encountering the same issue, both on Windows 10, R 4.1.0 and Debian 10, R 4.1.0
