### ISSUE TITLE
onLoad fails on Windows: cat not found. 

### ISSUE THREAD

**Issue by luke-a** [miraisolutions/xlconnect#132]
Hi all, 

Since I updated the package from 0.2-15 to 1.0.3, I cannot load it anymore - it fails with 

```
 Fehler: package or namespace load failed for ‘XLConnect’:
 .onLoad in loadNamespace() für 'XLConnect' fehlgeschlagen, Details:
  Aufruf: system2("cat", c("/etc/*-release"), stdout = TRUE, stderr = TRUE)
  Fehler: '"cat"' not found 
```

My `sessionInfo()` is: 
```
R version 3.6.2 (2019-12-12)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3       rstudioapi_0.10  magrittr_1.5     tidyselect_1.1.0 R6_2.4.1         rlang_0.4.7      stringr_1.4.0    dplyr_1.0.0     
 [9] tools_3.6.2      xfun_0.19        tinytex_0.28     ellipsis_0.3.0   tibble_3.0.3     lifecycle_0.2.0  crayon_1.3.4     rJava_0.9-13    
[17] purrr_0.3.3      vctrs_0.3.6      glue_1.4.1       stringi_1.4.6    compiler_3.6.2   pillar_1.4.3     generics_0.0.2   writexl_1.2     
[25] lubridate_1.7.4  pkgconfig_2.0.3 
```

**Comment by howerg** [comment]
Same issue for me:  

Loading required package: XLConnect
Error: package or namespace load failed for ‘XLConnect’:
 .onLoad failed in loadNamespace() for 'XLConnect', details:
  call: system2("cat", c("/etc/*-release"), stdout = TRUE, stderr = TRUE)
  error: '"cat"' not found


Session specifics:
R version 4.0.5 (2021-03-31) -- "Shake and Throw"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

**Comment by spoltier** [comment]
Please see the workaround: https://github.com/miraisolutions/xlconnect/issues/122#issuecomment-811001131
In summary, you need to install and make sure `cat.exe` is on the PATH. This can be done by installing git for windows.

Will follow up.

**Comment by spoltier** [comment]
Tested installing the source package - in this case the error doesn't occur, which explains why the checks / tests succeeded.
(used
```R
install.packages("XLConnect", type="source",INSTALL_opts=c("--no-multiarch"))
```)

**Comment by howerg** [comment]
Yes, that works, thank you very much!

**Comment by rweingarten** [comment]
I also had this issue and tried the work around with installing at source but continued to get the "Error: package or namespace load failed for ‘XLConnect’:
 .onLoad failed in loadNamespace() for 'XLConnect', details:
  call: system2("cat", c("/etc/*-release"), stdout = TRUE, stderr = TRUE)
  error: '"cat"' not found" 

Is there another workaround way to download and load the XLConnect? 


My session info: 
![image](https://user-images.githubusercontent.com/13630271/115469265-4d924d00-a202-11eb-80dc-8d779b7f7c72.png)

**Comment by Arbitrageur** [comment]
I had a similar issue.
And I think the function 'javaCheck'(R/onLoad.R) might be related to it.

In my case, 'java -version' output is:
```
java version "15" 2020-09-15
```
And, the following code in '.onLoad' function
```r
regexpr("[0-9]+\\.[0-9\\.]*", rawVersion[1])
```
cannot detect the version number "15"

**Comment by spoltier** [comment]
@rweingarten You need to have `cat` on your PATH. This should be enforced by installing from source because that requires RTools, which requires [mingw64](http://mingw-w64.org/doku.php).
To test it, just execute `cat` in a cmd prompt (not Powershell).

@Arbitrageur the Java issue is a different problem. Please open a different issue and mention which java (Red Hat, Oracle, adoptopenjdk) you did install, and whether this the full output of `java -version` (or are there further lines).

**Comment by spoltier** [comment]
If you have no _cat_ installed, you can try to install the [fixed Windows binary package](https://drive.google.com/file/d/1qd_-KhLk-5afIGBI4OZqk0OeAMrlktau/view?usp=drivesdk)

```R
install.packages("XLConnect.zip")
```

**Comment by spoltier** [comment]
If you are experiencing this issue, please make sure you are using XLConnect 1.0.4 or later.
