### ISSUE TITLE
Package not loading after upgrade RStudio to 1.4.1106

### ISSUE THREAD

**Issue by abellanandres** [miraisolutions/xlconnect#135]
Dear colleagues,

After I have been using XLConnect succesfully since I have upgrade RStudio from 1.3 to 1.4.116.

I can install de package.... get this message: 

"package ‘XLConnect’ successfully unpacked and MD5 sums checked
The downloaded binary packages are in
	C:\.....\AppData\Local\Temp\RtmpQHZZwn\downloaded_packages"

But when a try to load it I get the next error:

"Error: package or namespace load failed for ‘XLConnect’:
 .onLoad failed in loadNamespace() for 'XLConnect', details:
  call: if (twoFirst == "1.") {
  error: argumento tiene longitud cero
Además: Warning message:
In system2("java", c("-version"), stdout = TRUE, stderr = TRUE) :
  comando ejecutado '"java" -version' tiene estatus 2"

Any help or suggestions would be appreciate.
Thanks in advance.

**Comment by abellanandres** [comment]
Excuse me, I did not say R version: 4.0.5 
and java environment: 
java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) Client VM (build 25.202-b08, mixed mode)

**Comment by spoltier** [comment]
Hi @abellanandres, can you provide the exact output of `java -version` on the command line ?
Thanks

**Comment by abellanandres** [comment]
Hi @spoltier , here it is:

java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) Client VM (build 25.202-b08, mixed mode)

Thank you in advance!

**Comment by spoltier** [comment]
> I had a similar issue.
> And I think the function 'javaCheck'(R/onLoad.R) might be related to it.
> 
> In my case, 'java -version' output is:
> 
> ```
> java version "15" 2020-09-15
> ```
> 
> And, the following code in '.onLoad' function
> 
> ```r
> regexpr("[0-9]+\\.[0-9\\.]*", rawVersion[1])
> ```
> 
> cannot detect the version number "15"

@Arbitrageur tracking your problem under this as well

**Comment by spoltier** [comment]
Hi @abellanandres, thanks for the info. I'm having trouble reproducing the issue. Can you run the following R code on your system and let me know what the output is?
```R
> system2("java", c("-version"), stdout = TRUE, stderr = TRUE)
```

**Comment by abellanandres** [comment]
Hi @spoltier! thanks for the help, here you are:

> system2("java", c("-version"), stdout = TRUE, stderr = TRUE)
[1] "Error: Registry key 'Software\\JavaSoft\\Java Runtime Environment'\\CurrentVersion'"
[2] "has value '1.8', but '1.7' is required."                                            
[3] "Error: could not find java.dll"                                                     
[4] "Error: Could not find Java SE Runtime Environment."                                 
attr(,"status")
[1] 2
Warning message:
In system2("java", c("-version"), stdout = TRUE, stderr = TRUE) :
  comando ejecutado '"java" -version' tiene estatus 2

**Comment by spoltier** [comment]
@abellanandres looks like you may have an issue in your windows PATH. See https://stackoverflow.com/questions/29697543/registry-key-error-java-version-has-value-1-8-but-1-7-is-required#29769311
