### ISSUE TITLE
package or namespace load failed for ‘XLConnect’:

### ISSUE THREAD

**Issue by larseckle** [miraisolutions/xlconnect#137]
Hi,

having a problem to get XLConnect to work after upgrading to

R 4.0.3:

R version 4.0.3 (2020-10-10) -- "Bunny-Wunnies Freak Out"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

**Installing XLConnect 1.0.3 is OK**

 install.packages("XLConnect")
 パッケージを ‘C:/Users/Neptune/Documents/R/win-library/4.0’ 中にインストールします 
 (‘lib’ が指定されていないため) 
 --- このセッションで使うために、CRAN のミラーサイトを選んでください --- 
 URL 'https://ftp.fau.de/cran/bin/windows/contrib/4.0/XLConnect_1.0.3.zip' を試しています 
Content type 'application/zip' length 29498926 bytes (28.1 MB)
downloaded 28.1 MB

 パッケージ ‘XLConnect’ は無事に展開され、MD5 サムもチェックされました 

 ダウンロードされたパッケージは、以下にあります 
        C:\Users\Neptune\AppData\Local\Temp\RtmpGk3AvO\downloaded_packages 

**But loading it throws an error:**

library(XLConnect)
 エラー: package or namespace load failed for ‘XLConnect’:
  .onLoad は loadNamespace()（'XLConnect' に対する）の中で失敗しました、詳細は: 
  call: system2("cat", c("/etc/*-release"), stdout = TRUE, stderr = TRUE) 
  error: '"cat"' not found 
 追加情報:  警告メッセージ: 
 パッケージ ‘XLConnect’ はバージョン 4.0.5 の R の下で造られ

How can this be fixed?  XL Connect used to work for me before upgrading.

Thank you!

**Comment by larseckle** [comment]
Windows 10
java version "1.8.0_291"
Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.291-b10, mixed mode)

**Comment by davidbudzynski** [comment]
I'm having the same issue

**Comment by davidbudzynski** [comment]
This seems to be an issue only with Windows, tested the same package on Linux and everything seems to be working fine

**Comment by spoltier** [comment]
Duplicate of #132
