### ISSUE TITLE
Feature Request:  Use separate class loaders

### ISSUE THREAD

**Issue by Mosk915** [miraisolutions/xlconnect#142]
Per #79, the xlconnect package conflicts with the xlsx package because they share a Java dependency.  However, with s-u/rJava#250, it should now be possible to prevent this.  Would it be possible to apply this enhancement from rJava?

**Comment by spoltier** [comment]
Note: per #242, it is still not possible to use XLConnect after loading xlsx, as xlsx has not upgraded to use a separate classloader. Loading xlsx loads POI in the shared classloader, which will prevent XLConnect from working (as the shared classloader has priority).
