### ISSUE TITLE
cloneSheet doesn't seems to copy and rename the named regions as a copy of a sheet does in excel.

### ISSUE THREAD

**Issue by RedemptionArc** [miraisolutions/xlconnect#145]
Hi,

Trying to create a template form in excel that needs to be replicated and completed from R.
Problem is that when you copy the sheet using cloneSheet the local declared name spaces are not renamed and are still pointing to the original sheet.

Thanks for your help,
Michael.

**Comment by spoltier** [comment]
Hi  @RedemptionArc - would you expect to be able to reference the name within a specific worksheet ? If so we plan to add this with issue #37.

**Comment by RedemptionArc** [comment]
Hi,

Yes. The plan is indeed to reference the name within a specific worksheet (a bit like local names).

Another issue I'm having, but I'm not sure it's related to XLConnect is that, other than restarting the R session, there seems to be no way to drop the connection.

Regards,
Michael.

**Comment by spoltier** [comment]
Closing as this is covered by on #37
