### ISSUE TITLE
Support Java 17

### ISSUE THREAD

**Issue by spoltier** [miraisolutions/xlconnect#149]
CRAN is forcing us to support Java 17 because this is the first LTS version available on M1 Macs.

**Comment by marcschwartz** [comment]
Hi,

I just updated to an M1 based MacBook Pro, and perhaps naively installed the Azul openJDK Java JRE version 18, which is the latest version that natively supports the M1 chip.

After the fact, I noted that XLConnect supports up to version 17, having noted this issue from last year regarding version 17, and the details on CRAN regarding java version requirements.

Thus, I uninstalled version 18 and installed version 17.

In the course of tracking down this issue, I noted that there appears to be a typo in the error message in line 50 of onLoad.R:

https://github.com/miraisolutions/xlconnect/blob/master/R/onLoad.R

where it has:

if (jvn<8 || jvn>17) stop(paste0("XLConnect is compatible with Java versions **8 to 16**. Detected java version: ",jv))

and presumably should be "**8 to 17**".

Also, as a related issue, is there a plan to support version 18?

Thanks!
