### ISSUE TITLE
Wrong Java Version being pulled for Windows --- Always returns 4

### ISSUE THREAD

**Issue by gonzalezbensmol** [miraisolutions/xlconnect#156]
The code here:
`jv <- regmatches(rawVersion[1], regexpr("[0-9\\.]+", rawVersion[1]))`
always returns a 4 on Windows for me since it parses the top line: 
```
[1] "Picked up JAVA_TOOL_OPTIONS: -Dlog4j.formatMsgNoLookups=true"      
[2] "java version \"1.8.0_321\""                                        
[3] "Java(TM) SE Runtime Environment (build 1.8.0_321-b07)"             
[4] "Java HotSpot(TM) Client VM (build 25.321-b07, mixed mode, sharing)"
```
I am wondering if this is correct since Linux pulls the correct version and looks at the first line as well?

If I change the code to 
`jv <- regmatches(rawVersion[2], regexpr("[0-9\\.]+", rawVersion[2]))`
the correct java version is getting pulled.

**Comment by spoltier** [comment]
Thanks. We'll have to change this to look for the line containing the Java version, since this will depend on system configuration.

**Comment by spoltier** [comment]
As part of the fix, we should trigger the situation above in some of our CI scenarios, e.g. in the windows case. Possibly even with multiple relevant variables.
