### ISSUE TITLE
Switch to v2 r-lib/actions

### ISSUE THREAD

**Issue by Chargothrond** [miraisolutions/xlconnect#159]
This is by now the actively-maintained and improved version of r-related actions.

See https://github.com/r-lib/actions/releases/tag/v2

**Comment by spoltier** [comment]
@Chargothrond once you open a (draft) PR, the checks should run.

**Comment by Chargothrond** [comment]
I have created a draft PR now: https://github.com/miraisolutions/xlconnect/pull/160
