### ISSUE TITLE
Unable to load package in R studio

### ISSUE THREAD

**Issue by hkarun** [miraisolutions/xlconnect#176]
Dear Miraisolutions,
I am new to Rstudio and trying to use XL Connect. Here is the problem I am facing .

......................................................................
> install.packages("XLConnect")
trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/XLConnect_1.0.5.tgz'
Content type 'application/x-gzip' length 29539285 bytes (28.2 MB)
==================================================
downloaded 28.2 MB

The downloaded binary packages are in
	/var/folders/1l/s_jryxyd6_g6rqprtsxg0tfc0000gn/T//Rtmplwiw7E/downloaded_packages
> library(XLConnect)
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.

Error: package or namespace load failed for ‘XLConnect’:
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: fun(libname, pkgname)
  error: JVM could not be found
In addition: Warning messages:
1: In system("/usr/libexec/java_home", intern = TRUE) :
  running command '/usr/libexec/java_home' had status 1
2: In fun(libname, pkgname) :
  Cannot find JVM library 'NA/lib/server/libjvm.dylib'
Install Java and/or check JAVA_HOME (if in doubt, do NOT set it, it will be detected)

.................

Can you please help me resolve this issue?
Thanks and regards,
Honey Karun

**Comment by spoltier** [comment]
Hi @hkarun,

Please see the rstudio [documentation](https://solutions.rstudio.com/r/using-rjava/#setup-java-support-in-r). The rJava [README](https://github.com/s-u/rJava#troubleshooting) may also be useful. The first step will be to install Java on your machine (this is assuming you have installed rstudio and aren't using rstudio server or another hosted version).

**Comment by spoltier** [comment]
@hkarun please open a new ticket with more information if you were not able to solve the problem.
