### ISSUE TITLE
Problem XLConnect 1.0.6 with Java on MacOS

### ISSUE THREAD

**Issue by schneik3** [miraisolutions/xlconnect#180]
There seems to be a problem with XLConnect v1.0.6 and Java and MacOS. 

Just try running the lines:
"## Not run: "
"# Load workbook; create if not existing"
wb <- loadWorkbook("XLConnect.xlsx", create = TRUE)

-- By the way I guess "Not" should be replaced by "Note"

I am receiving the error:

NoClassDefFoundError (Java): org/openxmlformats/schemas/spreadsheetml/x2006/main/CTCellStyles

Regarding Java I have have zulu-8 installed:
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (Zulu 8.58.0.13-CA-macos-aarch64)

The problem does not occur if I downgrade to XLConnect v1.0.5.

Thx in advance!

**Comment by spoltier** [comment]
Thanks for reporting this issue, @schneik3 !
Can you provide 
* the R console output when loading XLConnect
* the listing of the java/ directory in the XLConnect install directory? 
?

**Comment by schneik3** [comment]
Dear spoltier,
thanks so much for your quick reply! 

If I am running:
>  wb <- loadWorkbook("XLConnect.xlsx", create = TRUE)
The R console output is:
Fehler: NoSuchFieldError (Java): Factory

The second question is not clear to me. Where would I find the listening of the java/directory? in the XLConnect directory?

Hence I tried to reinstall the XLConnect package hoping it shows the path. 
Now when running
>  wb <- loadWorkbook("XLConnect.xlsx", create = TRUE)
The R console output is:

I am receiving this error:
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...

**Comment by spoltier** [comment]
@schneik3  you can find the directory using `libPaths()` in R - type  `?.libPaths` in your R console for details. This is where all your R packages are installed. You should see an _XLConnect_ directory under this path. _.libPaths_ may return several directories in which case you should look in each of them.

**Comment by spoltier** [comment]
Closing as I haven't received any feedback
