### ISSUE TITLE
Feature Request:  NA handling

### ISSUE THREAD

**Issue by chuckcoleman** [miraisolutions/xlconnect#193]
### What's the problem this feature will solve?

Right now, when I write NAs to a worksheet, they are converted to 0s.  The problem is that NA != 0 for my problem.  As a result, my output has deceptive values.

### Describe the solution you'd like

I want the option to set NAs to values other than 0.  At the very least, having them appear as blanks in the spreadsheet will work.

### Alternative Solutions

I've tried to find packages that let me output formatted Excel files.  XLConnect is simple and the only one I've found so far.  I created a formatted template and everything worked but the NA handling.

**Comment by spoltier** [comment]
@chuckcoleman see https://www.rdocumentation.org/packages/XLConnect/versions/1.0.7/topics/setMissingValue-methods
or `help(setMissingValue)` in your R prompt.
Check that the provided example works for you (the built-in `airquality` data should have NAs).
If applying this does not work, make sure the data you write to the Excel sheet actually contains NAs.
In a modern R prompt, you should be able to page through XLConnect methods by typing `XLConnect::` to trigger the auto-complete.

**Comment by chuckcoleman** [comment]
I ended up using openxlsx, which does the missing value handling in its data copy function.  This was a bit easy to miss, not being mentioned in the main vignette.
