### ISSUE TITLE
Issue with [] formulas in tables

### ISSUE THREAD

**Issue by dmenne** [miraisolutions/xlconnect#21]
Followup to :
http://stackoverflow.com/questions/17671290/read-excel-tables-not-simple-named-ranges

This works for the sample file I uploaded first. I made a small change, now using
the [Age] syntax to refer to a column in a table, which I believe is one of the most useful and least known ones in Excel. The example below fails, giving NA, for this case.

http://www.menne-biomed.de/uni/ExcelTables.xlsx

Dieter

require(XLConnect)
sampleFile = "ExcelTables.xlsx"
wb = loadWorkbook(sampleFile)
readTable(wb, sheet = "ExcelTable", table = "TableName")

**Comment by spoltier** [comment]
As of writing, the limitation in POI is still listed at the link above.
