### ISSUE TITLE
Add hyperlink support

### ISSUE THREAD

**Issue by lambiase** [miraisolutions/xlconnect#51]
Apache POI has cell hyperlink methods which are not exposed in XLConnect:

https://poi.apache.org/apidocs/org/apache/poi/ss/usermodel/Cell.html#getHyperlink()
https://poi.apache.org/apidocs/org/apache/poi/ss/usermodel/Cell.html#removeHyperlink()
https://poi.apache.org/apidocs/org/apache/poi/ss/usermodel/Cell.html#setHyperlink(org.apache.poi.ss.usermodel.Hyperlink)

It would be helpful to have this functionality exposed in XLConnect.

**Comment by dominiqueemmanuel** [comment]
Hi,

Yes, moreover this functionality is available in other R packages: so it would be nice to have it in `XLConnect`...

Best regards,
Dom

**Comment by martinstuder** [comment]
Available in master branch
