### ISSUE TITLE
Error: NoClassDefFoundError (Java): com/microsoft/schemas/office/x2006/encryption/EncryptionDocument$Factory

### ISSUE THREAD

**Issue by mmoisse** [miraisolutions/xlconnect#54]
When I install the xlconnect package from github and then try to give open a password protected xlsx file I get a NoClassDefFoundError Java error. This is however solved when I replace `ooxml-schemas-1.3.jar` with version 3.1 http://mvnrepository.com/artifact/org.apache.poi/poi-ooxml-schemas/3.10-FINAL

    > install_github("xlconnectjars", username = "miraisolutions", ref = "master")
    > install_github("xlconnect", username = "miraisolutions", ref = "master")
    > library(XLConnect)
    > loadWorkbook("~/Downloads/test.xlsx", password="pass")
    Error: NoClassDefFoundError (Java): com/microsoft/schemas/office/x2006/encryption/EncryptionDocument$Factory

**Comment by martinstuder** [comment]
Hi,

thank you for your report! Would you mind attaching a sample file here that we can use to reproduce the issue?

Thanks,
Martin

**Comment by martinstuder** [comment]
Not reproducible
