### ISSUE TITLE
Error: NoSuchFieldError (Java): DONT_MOVE_AND_RESIZE

### ISSUE THREAD

**Issue by SiegHartR** [miraisolutions/xlconnect#55]
Every time a for loop addImage I get this error :
Error: NoSuchFieldError (Java): DONT_MOVE_AND_RESIZE

I need to restart R to manage to print the piecharts to my sheets.

I tried also to detach all the previous packaged loaded and run only png and plotrix and of course xlconnect...but the error appears anyway.

without adding the addImage function all the sheets with the content get printed.

Thank you

**Comment by martinstuder** [comment]
Could you provide a reproducible example that illustrates the problem? It would also be good if you could provide us with the output of `sessionInfo()` in R and the version of Java (run `java -version` on the OS command line) that you are using.

**Comment by martinstuder** [comment]
I guess this is the same underlying problem as #58 - can you confirm?

**Comment by martinstuder** [comment]
Not reproducible - please reopen with a reproducible example if you happen to see this error again.
