### ISSUE TITLE
Issue with reading zeros formated as "-"

### ISSUE THREAD

**Issue by lz1nwm** [miraisolutions/xlconnect#56]
I have a problem with reading zeros formatted as "-" in xls file with `xlconnect` 0.2-12. Please, run the code below and check Col12. Is it a bug or I'm missing something? If I'm not wrong, there was no issue to read these zeroes with `xlconnect` 0.2-11.

```R
library(XLConnect) 
path = "http://www.bnb.bg/bnbweb/groups/public/documents/bnb_download/s_ir_interestrates_aa05_en.xls"

download.file(path, destfile = "s_ir_interestrates_aa05_en.xls", mode="wb")

dt <- readWorksheetFromFile(
        's_ir_interestrates_aa05_en.xls',
        sheet = 1,
        header = F,
        startRow = 8, 
        startCol = 1)
```

**Comment by martinstuder** [comment]
Hi, thanks for the report! Cell L84 is a string which leads Col12 to be a character - this is working as expected. Also note that there are other rows with text such as row 124. If you want to force certain column types you may use the `colTypes` argument.
