### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by bigno250** [miraisolutions/xlconnect#57]
I can work around by writing to .xls, but I'm getting the error below when using XLConnect to write .xlsx spreadsheets.  Is this a Java problem on my computer, or something with the version of the package I'm running?  XLConnect has been running fine for me until just recently.

Software:
XLConnect 0.2-12
XLConnectJars 0.2-12
R version 3.2.5 (2016-04-14)   Platform: x86_64-w64-mingw32/x64 (64-bit)
Java Version 8 build 1.8.9-92-b14

Error: NoSuchMethodError (Java): org.apache.xmlbeans.XmlBeans.typeSystemForClassLoader(Ljava/lang/ClassLoader;Ljava/lang/String;)Lorg/apache/xmlbeans/SchemaTypeSystem;

**Comment by martinstuder** [comment]
Please provide a reproducible example (code and support files) that leads to this error. Also, it would be good if you could provide the output of `sessionInfo()` in R.

**Comment by martinstuder** [comment]
Not reproducible - please reopen with a reproducible example if the issue persists

**Comment by NabeelahB** [comment]
Hi,
I'm also facing the same issue. When I'm trying to read a worksheet using XLConnect this is the error i get:
Error: NoSuchMethodError (Java): org.apache.poi.ss.usermodel.Cell.getCellTypeEnum()Lorg/apache/poi/ss/usermodel/CellType;

below is my sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] dplyr_0.7.1          stringr_1.2.0        XLConnect_0.2-13     XLConnectJars_0.2-13
 [5] shiny_1.0.3          xlsx_0.5.7           xlsxjars_0.6.1       rJava_0.9-8         
 [9] readxl_1.0.0         lubridate_1.6.0

and this is my java version:
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Do advice what to do.

**Comment by teemo48** [comment]
Same problem.  

R version 3.3.3 (2017-03-06)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Sierra 10.12.5

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] RColorBrewer_1.1-2   scales_0.4.1         ggplot2_2.2.1        readxl_0.1.1         XLConnect_0.2-13    
 [6] XLConnectJars_0.2-13 xlsx_0.5.7           xlsxjars_0.6.1       rJava_0.9-8          stringr_1.2.0       
[11] lubridate_1.6.0      reshape2_1.4.2       dplyr_0.5.0          plyr_1.8.4           magrittr_1.5        
[16] testthat_1.0.2 


java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468-11M4833)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)

**Comment by teemo48** [comment]
`
library(xlsx)
library(XLConnect)
library(readxl)

test.df = data.frame( C=c('a','b'), N=1:1)
test.df

write.xlsx( test.df, 'test.xlsx', row.names=FALSE)
in1 = read.xlsx('test.xlsx',1)
in1
in2 = read_excel('test.xlsx')
in2

# Fails
in3 = readWorksheetFromFile("test.xlsx",
                      sheet=1)
# Fails
writeWorksheetToFile('test2.xls', df, sheet=1)
`



CONSOLE LOG:
> library(xlsx)
> library(XLConnect)
> library(readxl)
> 
> test.df = data.frame( C=c('a','b'), N=1:1)
> test.df
  C N
1 a 1
2 b 1
> 
> write.xlsx( test.df, 'test.xlsx', row.names=FALSE)
> 
> in1 = read.xlsx('test.xlsx',1)
> in1
  C N
1 a 1
2 b 1
> 
> in2 = read_excel('test.xlsx')
> in2
# A tibble: 2 × 2
      C     N
  <chr> <dbl>
1     a     1
2     b     1
> 
> # Fails
> in3 = readWorksheetFromFile("test.xlsx",
+                       sheet=1)
Error: NoSuchMethodError (Java): org.apache.poi.ss.usermodel.Cell.getCellTypeEnum()Lorg/apache/poi/ss/usermodel/CellType;
> # Fails
> writeWorksheetToFile('test2.xls', df, sheet=1)
Error: NoSuchMethodError (Java): org.apache.poi.hssf.usermodel.HSSFWorkbook.getNumCellStyles()I
>

**Comment by teemo48** [comment]
`
cat("Reproducible")
library(xlsx)
library(XLConnect)
library(readxl)

test.df = data.frame( C=c('a','b'), N=1:1)
test.df

write.xlsx( test.df, 'test.xlsx', row.names=FALSE)

in1 = read.xlsx('test.xlsx',1)
in1

in2 = data.frame(read_excel('test.xlsx'))
in2

cat("Fails")
in3 = readWorksheetFromFile("test.xlsx",
                      sheet=1)
cat("Fails")
writeWorksheetToFile('test2.xls', df, sheet=1)`


CONSOLE LOG:
`
> cat("Reproducible")
Reproducible
> library(xlsx)
> library(XLConnect)
> library(readxl)
> 
> test.df = data.frame( C=c('a','b'), N=1:1)
> test.df
  C N
1 a 1
2 b 1
> 
> write.xlsx( test.df, 'test.xlsx', row.names=FALSE)
> 
> in1 = read.xlsx('test.xlsx',1)
> in1
  C N
1 a 1
2 b 1
> 
> in2 = data.frame(read_excel('test.xlsx'))
> in2
  C N
1 a 1
2 b 1
> 
> cat("Fails")
Fails
> in3 = readWorksheetFromFile("test.xlsx",
+                       sheet=1)
Error: NoSuchMethodError (Java): org.apache.poi.ss.usermodel.Cell.getCellTypeEnum()Lorg/apache/poi/ss/usermodel/CellType;
> cat("Fails")
Fails
> writeWorksheetToFile('test2.xls', df, sheet=1)
Error: NoSuchMethodError (Java): org.apache.poi.hssf.usermodel.HSSFWorkbook.getNumCellStyles()I
>  `

**Comment by martinstuder** [comment]
Packages `XLConnect` and `xlsx` are not compatible and can not be loaded at the same time. Reason is that `XLConnect` (with `XLConnectJars`) and `xlsx` with (`xlsxjars`) ship with different versions of Apache POI. Depending on which package is loaded first, the other package won't work.

**Comment by teemo48** [comment]
Thanks!  Don’t know how long it would have taken to figure that out.

This fact may be around somewhere, but it certainly didn’t come up with a lot of googling trying to debug.

Might be worth making it more finable.
Certainly would have helped me, anyway.

**Comment by HadyShaaban** [comment]
> Packages `XLConnect` and `xlsx` are not compatible and can not be loaded at the same time. Reason is that `XLConnect` (with `XLConnectJars`) and `xlsx` with (`xlsxjars`) ship with different versions of Apache POI. Depending on which package is loaded first, the other package won't work.

thank you very much,
I faced same problem but using your solution the problem solved. Much appreciated.
