### ISSUE TITLE
Error: NoSuchFieldError (Java): DONT_MOVE_AND_RESIZE   || SECOND REPORT

### ISSUE THREAD

**Issue by IMScandalous** [miraisolutions/xlconnect#58]
The follwing error/bug has already been reported by an user, but he hasn't provided any examples. I will do that now.

He is the reproducible example error: 

-----------------------------------------------------------------------------------

working_path="C:/Users/Admin/Desktop/KOS Joël/Scripts def"

library(rJava)
library(xlsxjars)
library(xlsx)

Results_Workbook <- createWorkbook(type='xlsx')
sheet.1 <- createSheet(Results_Workbook, sheetName = "First_sheet")
saveWorkbook(Results_Workbook, paste(working_path,"/WB.xlsx",sep=""))

library(XLConnectJars)
library(XLConnect)

wb = XLConnect::loadWorkbook(paste(working_path,"/WB.xlsx",sep=""), create=FALSE)

createName(wb, name = "MFA_simple_plot_axes_12", formula = "First_sheet!$B$4:$R$58")
addImage(wb, filename = paste(working_path,'/Résultat graphique MFA Simple plot axes 12.emf',sep=""),
         name="MFA_simple_plot_axes_12", originalSize = FALSE)

createName(wb, name = "MFA_simple_plot_axes_13", formula = "First_sheet!$B$62:$R$118")
addImage(wb, filename = paste(working_path,'/Résultat graphique MFA Simple plot axes 13.emf',sep=""),
         name="MFA_simple_plot_axes_13", originalSize = FALSE)

createName(wb, name = "MFA_simple_plot_axes_23", formula = "First_sheet!$B$122:$R$176")
addImage(wb, filename = paste(working_path,'/Résultat graphique MFA Simple plot axes 23.emf',sep=""),
         name="MFA_simple_plot_axes_23", originalSize = FALSE)

XLConnect::saveWorkbook(wb,paste(working_path,"/WB.xlsx",sep=""))

----------------------------------------------------------------------------------------------------
 Explanation: 
I use the xlsx package to create worksbooks and usually also to add dataframes and format them,add titles,...

I then use XLConnect to add images, because it's it supports EMF format, while xlsx doesn't seem to. (They say they do but it doesn't work)

The problem is that I keep getting the following error, everytime I try to add an image.

Error: NoSuchFieldError (Java): DONT_MOVE_AND_RESIZE

I attached three EMF files that serve for the example code.

[Dateien.zip](https://github.com/miraisolutions/xlconnect/files/415370/Dateien.zip)
---------------------------------------------------------------------------------------

Here is the session info: 

> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252
[4] LC_NUMERIC=C                   LC_TIME=French_France.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] XLConnect_0.2-12     XLConnectJars_0.2-12 xlsx_0.5.7           xlsxjars_0.6.1       rJava_0.9-8         

loaded via a namespace (and not attached):
[1] tools_3.2.3

it's pretty important for me be able to export EMFs and I has already worked sometimes but in the case above for example I get the error.

Best regards,

Joël

**Comment by IMScandalous** [comment]
Here is something that I saw from testing my reproducible error code.

The problem comes most likely from an interference between xlsx and XLConnect.

Indeed if I first run just the first part of the code, up until the Workbook is by by the xlsx function; then close R, open it again and run the second part, the error disappear.

Note that if I try to detach the xlsx package before running the part with XLConnect, the errors persists

**Comment by martinstuder** [comment]
You can't simply detach a package that contains JAR files as the underlying JVM was already initialized and corresponding classes have been loaded. In your case with xlsx and XLConnect, xlsx already initializes the different versions of POI classes that will be incompatible with XLConnect. As such, you shouldn't (can't) use xlsx and XLConnect in the same R session.
