### ISSUE TITLE
not able to read Chinese from excel

### ISSUE THREAD

**Issue by dhc1434** [miraisolutions/xlconnect#59]
When the excel cell contains Chinese characters and imported by the function readWorksheetFromFile, the parameter displays some code like "<U+81ED><U+6C27>", which is not correct. Is it possible to read Chinese characters?

**Comment by martinstuder** [comment]
Hi,
can you submit a reproducible example (sample file and code) that illustrates the problem?
Thanks,
Martin

**Comment by dhc1434** [comment]
Hi I have solved this issue, we need to set the locale of R by the
following code:

    Sys.setlocale(category = "LC_ALL", locale = "chs") #cht for traditional
Chinese, etc.

Thank you very much for the great package! It's one of my most frequently
used packages.

Best regards,
Hancheng DAI
------------------------------
*PhD, Research Associate*
Integrated Environment and Economics Section
Center for Social and Environmental Systems Research
National Institute for Environmental Studies
16-2 Onogawa, Tsukuba-City, Ibaraki, 305-8506 Japan
TEL: +81-29-850-2355 / Fax: +81-29-850-2422
Email: *dai.hancheng@nies.go.jp <dai.hancheng@nies.go.jp>*
Connect me at*: Google scholar
<https://scholar.google.co.jp/citations?user=9Jp7TgMAAAAJ&hl=en> or
ResearchGate
<https://www.researchgate.net/profile/Hancheng_Dai>*
------------------------------

**Comment by martinstuder** [comment]
Ok - great to hear you got the issue resolved!
