### ISSUE TITLE
Error: NoClassDefFoundError (Java): com/microsoft/schemas/office/x2006/encryption/EncryptionDocument$Factory

### ISSUE THREAD

**Issue by pkopps** [miraisolutions/xlconnect#61]
```r 
sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.5 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8          LC_NUMERIC=C                 
 [3] LC_TIME=en_US.UTF-8           LC_COLLATE=en_US.UTF-8       
 [5] LC_MONETARY=en_US.UTF-8       LC_MESSAGES=en_US.UTF-8      
 [7] LC_PAPER=en_US.UTF-8          LC_NAME=en_US.UTF-8          
 [9] LC_ADDRESS=en_US.UTF-8        LC_TELEPHONE=en_US.UTF-8     
[11] LC_MEASUREMENT=en_US.UTF-8    LC_IDENTIFICATION=en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rJava_0.9-6   ROracle_1.2-2 DBI_0.5-1    

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.8          XLConnectJars_0.2-12 assertthat_0.1      
 [4] grid_3.3.0           plyr_1.8.4           gtable_0.2.0        
 [7] XLConnect_0.2-12     scales_0.4.1         ggplot2_2.2.0       
[10] lazyeval_0.2.0       tools_3.3.0          munsell_0.4.3       
[13] colorspace_1.2-6     knitr_1.15           tibble_1.2 
```

```r
> XLConnect::loadWorkbook("PATH", password = "PASSWORD")

Error: NoClassDefFoundError (Java): com/microsoft/schemas/office/x2006/encryption/EncryptionDocument$Factory
```

After searching this is one of the only Excel R Packages that allows you to open password protected workbooks, hope this can be fixed

**Comment by martinstuder** [comment]
I failed to reproduce this issue using XLConnect 0.2-12:

```
> require(XLConnect)
Loading required package: XLConnect
Loading required package: XLConnectJars
XLConnect 0.2-12 by Mirai Solutions GmbH [aut],
  Martin Studer [cre],
  The Apache Software Foundation [ctb, cph] (Apache POI, Apache Commons
    Codec),
  Stephen Colebourne [ctb, cph] (Joda-Time Java library),
  Graph Builder [ctb, cph] (Curvesapi Java library)
http://www.mirai-solutions.com ,
http://miraisolutions.wordpress.com
> wb = loadWorkbook("~/Downloads/test.xlsx", password = "test")
> readWorksheet(wb, sheet = "test")
  a b c
1 1 4 7
2 2 5 8
3 3 6 9
```
Could you upload a sample file that exhibits the issue?

**Comment by khalani** [comment]
I just ran into this same issue. The included file seems to exhibit the same issues. 
[TestWorkbook.xlsx](https://github.com/miraisolutions/xlconnect/files/794219/TestWorkbook.xlsx)

**Comment by martinstuder** [comment]
Ok, thanks - I'm able to reproduce the issue with that file.

**Comment by martinstuder** [comment]
Will need to include poi-ooxml-schemas in order to get rid of that issue.

**Comment by hmenag1** [comment]
I'm having the same issue too. The error is the same:
Error: NoClassDefFoundError (Java): com/microsoft/schemas/office/x2006/encryption/EncryptionDocument$Factory
Any help would be greatly appreciated.
Thank you.

**Comment by dalewsteele** [comment]
On Mac OS 10.11.16 and R 3.4.0 and lastest version XLConnect installed from github, loading password protected worksheet fails with "Error: EncryptedDocumentException (Java): Export Restrictions in place - please install JCE Unlimited Strength Jurisdiction Policy files"

`> library(XLConnect)`
Loading required package: XLConnectJars
XLConnect 0.2-13 by Mirai Solutions GmbH [aut],
  Martin Studer [cre],
  The Apache Software Foundation [ctb, cph] (Apache POI),
  Graph Builder [ctb, cph] (Curvesapi Java library)
http://www.mirai-solutions.com , http://miraisolutions.wordpress.com

`> workbook = loadWorkbook("TestWorkbook.xlsx",password = "pass")`
Error: EncryptedDocumentException (Java): Export Restrictions in place - please install JCE Unlimited Strength Jurisdiction Policy files
