### ISSUE TITLE
Suppress "Value is not available" warnings

### ISSUE THREAD

**Issue by charlie-roosen** [miraisolutions/xlconnect#62]
When an empty Excel cell is read, warnings appear regarding "Value is not available":

          6: Error detected in cell G6 - Value is not available
          7: Error detected in cell G7 - Value is not available
          8: Error detected in cell G8 - Value is not available
          9: Error detected in cell G9 - Value is not available

Reading an Excel region with empty cells is in many cases normal behaviour where no warning is desired.

It would be helpful to have a way to suppress these warnings, either as a global option or an argument to readNamedRegion().

**Comment by martinstuder** [comment]
The recommended way of doing this is to use R's suppressWarnings. In many cases the warnings have been helpful to highlight potential issues.

**Comment by martinstuder** [comment]
Actually, if I'm not mistaken, the error only applies to formula-evaluated cells. A blank cell by itself should not issue such a warning.
