### ISSUE TITLE
Get all named regions

### ISSUE THREAD

**Issue by deanchen** [miraisolutions/xlconnect#63]
A get all named regions function similar to getNamedRegions in https://cran.r-project.org/web/packages/openxlsx/openxlsx.pdf will be helpful so we can read all named region data back in to R.

**Comment by lambiase** [comment]
Hi Dean,
have a look at the function "getDefinedNames".

**Comment by deanchen** [comment]
Thanks! Exactly what I needed, was searching the docs for namedRegion and missed that function.
