### ISSUE TITLE
Read/write named ranges with worksheet scope

### ISSUE THREAD

**Issue by bescoto** [miraisolutions/xlconnect#66]
It's very convenient now to read/write data into named ranges with "Workbook" scope.  But Excel also supports named ranges of worksheet scope.  For instance, sheets "Sheet1", "Sheet2", and "Sheet3" might all have a named range called "mydata".  Currently there doesn't seem to be any way to tell these apart or to write to one of them in particular:
~~~~
> getDefinedNames(wb, validOnly=TRUE)
[1] "mydata"    "mydata"    "mydata"
~~~~

**Comment by lambiase** [comment]
Duplicate of #37
