### ISSUE TITLE
OutOfMemoryError (Java): GC overhead limit exceeded

### ISSUE THREAD

**Issue by JMMouchel** [miraisolutions/xlconnect#67]
I work on a debian 8 system. R version 3.1.1. XLConnect version 0.2-10.

I observe memory overflow errors that seem to occur only when overwriting an existing xlsx file. The same code writing a non already existing file is ok. 

Starts with a "OutOfMemoryError (Java): GC overhead limit exceeded" when calling writeNamedRegion
Then error in ".jcall("RJavaTools", "Ljava/lang/Object;", "newInstance", .jfindClass(class),  : java.lang.OutOfMemoryError: GC overhead limit exceeded" when callin once more writeNamed region
Then error in ".jcall("RJavaTools", "Z", "hasField", .jcast(x, "java/lang/Object"),  : java.lang.OutOfMemoryError: GC overhead limit exceeded" when calling saveWorkbook

**Comment by martinstuder** [comment]
You need to increase the max Java heap size. See e.g.
* http://stackoverflow.com/questions/7963393/out-of-memory-error-java-when-using-r-and-xlconnect-package
* http://stackoverflow.com/questions/27153974/how-to-fix-outofmemoryerror-java-gc-overhead-limit-exceeded-in-r
