### ISSUE TITLE
R crash when loading xlconnectjars

### ISSUE THREAD

**Issue by piral** [miraisolutions/xlconnect#70]
R is chrashing when loading xlconnectjars. A new installation of the package ends with segmentation fault. This behaviour started after an upgrade of some packages in ubuntu 16.04. There are no other hints and I've no clue how to debug this problem.

**Comment by all4miller** [comment]
I experience the same issue on an a legacy system after installing updates Ubuntu 13.13.

If I start R and then `library(XLConnect)` it segfaults

**Comment by martinstuder** [comment]
It seems to be related to some Ubuntu updates. In fact, it is not directly related to XLConnect since the issue can be reproduced as follows in R:

```
require(rJava)
.jinit()
```

**Comment by martinstuder** [comment]
It seems this is related to a bug in kernel 4.4.0-81-generic:
https://askubuntu.com/questions/927746/eclipse-crashes-with-linux-kernel-4-4-0-81-generic

Indeed, as the article points out, the following does not trigger a segmentation fault in my case:

```
options(java.parameters = "-Xss2048k")
require(rJava)
.jinit()

```
