### ISSUE TITLE
R crashes in library(XLConnect)

### ISSUE THREAD

**Issue by kforner** [miraisolutions/xlconnect#72]
similar to #70 in some ways:
R crashes when executing `library(XLConnect)`

A few puzzling elements:

- does not crash if you execute `loadNamespace(XLConnect)` before  `library(XLConnect)`
- in a docker container, so with the exact same versions of R, packages and java, it does crashes
 on some computer but not on others. The kernel version where it crashes is 3.13.0-121-generic, does not crash on 4.4.0-75-generic
- `library(XLConnectJars)` does not crash
- `require(rJava);.jinit()` does not crash
- the crash happens in `.onLoad()`, in `XLConnectSettings(packageDescription(pkgname))`, and more precisely in `try(a <- .jcall("java/lang/Class", "Ljava/lang/Class;", "forName", 
    cl, TRUE, .jcast(.rJava.class.loader, "java.lang.ClassLoader"), 
    check = FALSE))`

The fix from #70 seems to work:
```
options(java.parameters = "-Xss2048k")
library(XLConnect)
```

```
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 8 (jessie)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C             
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base  
```

**Comment by martinstuder** [comment]
Yes, I think this is the same underlying reason as #70
