### ISSUE TITLE
XL Connect Java  No-Such Method Error 

### ISSUE THREAD

**Issue by rlmertens** [miraisolutions/xlconnect#73]
Dear all,

I get a strange Java Error whenever calling writeWorksheet(). The error code printed in the console is as follows: 

NoSuchMethodError (Java): org.apache.poi.ss.usermodel.Cell.setCellType(Lorg/apache/poi/ss/usermodel/CellType;)V

Strangely, I find that reinstalling the package rJava solves the issue and everything works as it should. However, whenever a new R instance is opened, the error reappears. Hence, every call to writeWorksheet require a previous re-installation of rJava. I have been able to replicate this error on several different PCs, all of them are running R.3.4.0. 

Does anybody know what is going on here? Thanks for your help in advance.

Kind regards,
Richard

**Comment by NabeelahB** [comment]
Hi,
I'm also facing the same issue. When I'm trying to read a worksheet using XLConnect this is the error i get:
Error: NoSuchMethodError (Java): org.apache.poi.ss.usermodel.Cell.getCellTypeEnum()Lorg/apache/poi/ss/usermodel/CellType;

below is my sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] dplyr_0.7.1          stringr_1.2.0        XLConnect_0.2-13     XLConnectJars_0.2-13
 [5] shiny_1.0.3          xlsx_0.5.7           xlsxjars_0.6.1       rJava_0.9-8         
 [9] readxl_1.0.0         lubridate_1.6.0

and this is my java version:
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Do advice what to do.

**Comment by martinstuder** [comment]
Packages `XLConnect` and `xlsx` are not compatible and can not be loaded at the same time. Reason is that `XLConnect` (with `XLConnectJars`) and `xlsx` with (`xlsxjars`) ship with different versions of Apache POI. Depending on which package is loaded first, the other package won't work.

**Comment by gloriousglory** [comment]
Thanks very much. In my case, I had to get rid of XLConnect, and use xlsx instead.
