### ISSUE TITLE
Reading "custom" text from xlsx file

### ISSUE THREAD

**Issue by JegorG** [miraisolutions/xlconnect#74]
I have a xlsx file which contain two rows, 18:20 and 10:10 in  row 1:2, column A.
It has two sheets with same data. When I try to read it in R using the following code:

```
library(XLConnect)

setwd("...")
book <- loadWorkbook("test.xlsx")

labels <- lapply(getSheets(book), readWorksheet, object = book, header = F)

# Returns some kind of date format

labels <- lapply(getSheets(book), readWorksheet, object = book, colTypes = "character", header = F)

# Same as above
```

What I get is 

```
1 1899-12-31 18:20:00
2 1899-12-31 10:10:00
```

Is it possible to fix somehow in readWorksheet without going through the Excel files and changing the format?

**Comment by martinstuder** [comment]
See https://stackoverflow.com/questions/21312173/how-can-i-retrive-the-time-only-with-xlconnect
