### ISSUE TITLE
Compilation issues on Single Candle/Ubuntu Xenial

### ISSUE THREAD

**Issue by leobelen** [miraisolutions/xlconnect#75]
Package installation after upgrading to R 3.4.1 "Single Candle" fails with segmentation fault on Ubuntu Xenial. We tried to copy the version used by R 3.4.0  "You Stupid Darkness", but that crashes R altogether.

**Comment by martinstuder** [comment]
Can you provide the package installation output? I don't think this is related to R 3.4.1 as I can install XLConnect on 3.4.1 without any problems. Are you sure this is not related to #70?
