### ISSUE TITLE
package "xlconnect" unusable after having used package "xlsx"

### ISSUE THREAD

**Issue by TillF** [miraisolutions/xlconnect#79]
Because of complementary functionality I want to use "xlconnect" after package "xlsx".
However, the code snippet, which works when issued alone, fails when executed after having used "xlsx" in the same session. 

````
#A: usage of xlsx ####
library(xlsx)
wb <- createWorkbook()
cs <- CellStyle(wb) +        #create a cell style
  Font(wb, heightInPoints=20) + 
  Fill(backgroundColor="lavender")
# unload package and its dependencies
try(detach("package:xlsx"    , unload=TRUE, force = TRUE), silent = TRUE)
try(detach("package:xlsxjars", unload=TRUE, force = TRUE), silent = TRUE)
try(detach("package:rJava", unload=TRUE, force = TRUE), silent = TRUE)

#B: usage of XLConnect ####
library(XLConnect)
wb <- XLConnect::loadWorkbook(file = paste0(tempfile(),".xlsx"), create = TRUE)  #create an empty xlsx -> error
````
Error message differs:
When called from RStudio:

> Error in .jfindClass(as.character(class)) : class not found

When called from R-console:

> Loading package: XLConnectJars
> Error: package or namespace load failed for ‘XLConnectJars’:
>  .onLoad in loadNamespace() für 'XLConnectJars' fehlgeschlagen, Details:
>  call: .jcall("java/lang/System", "S", "getProperty", "java.class.path")
>  error: RcallMethod: cannot determine object class
>   error: package ‘XLConnectJars’ could not be loaded

There is a complementary error when using the packages in the reverse order (block B before block A, https://github.com/dragua/xlsx/issues/95).

Is there a workaround for this except restarting R?

> > sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1
Matrix products: default
locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
[3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
loaded via a namespace (and not attached):
[1] compiler_3.5.0 rJava_0.9-9

**Comment by martinstuder** [comment]
You can't use XLConnect and xlsx in the same R session since they may have conflicting dependencies. More specifically XLConnectJars and xlsxjars may have conflicting Java dependencies (such as Apache POI).
