### ISSUE TITLE
XLConnect doesn't install for Java10

### ISSUE THREAD

**Issue by kilojoules** [miraisolutions/xlconnect#80]
Hello All,

XLConnect won't install for Java10. I'm pretty sure it relies on the `javah` library. which was removed from Java10.

Best,
Julian

**Comment by RolandASc** [comment]
This was an issue of the underlying `rJava` package, which has been upgraded on CRAN just one day before your issue post here :)
See https://cran.r-project.org/web/packages/rJava/index.html and https://github.com/s-u/rJava for reference.
