### ISSUE TITLE
Renaming a workbook

### ISSUE THREAD

**Issue by barthriley** [miraisolutions/xlconnect#84]
I would like to open a (more or less) blank workbook containing custom styles and use it as a template for other workbooks. I can not seem to find a way to do this in XLConnect. I tried the following:

wb <- loadWorkbook(templateFilename, create = FALSE)
wb@filename <- outputFilename
saveWorkbook(wb)

But this generated a FileNotFoundException, pointing to the template file.

Please advise.

Barth

**Comment by martinstuder** [comment]
Hi Barth, I guess what you are looking for is `saveWorkbook(wb, file=outputFilename)`. See also `help(saveWorkbook)` for more details.
