### ISSUE TITLE
Warning: Illegal reflective operation at first use of XLConnect-function

### ISSUE THREAD

**Issue by BaukjeStienstra** [miraisolutions/xlconnect#93]
The first time I use a function of the **XLConnect** package I get the next confusing warning:
```
> wb <- loadWorkbook("~/Test/earthquakes.xlsx", create = TRUE)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.poi.util.SAXHelper (file:/usr/share/R/library/xlsxjars/java/poi-ooxml-3.10.1-20140818.jar) to method com.sun.org.apache.xerces.internal.util.SecurityManager.setEntityExpansionLimit(int)
WARNING: Please consider reporting this to the maintainers of org.apache.poi.util.SAXHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

The next time I use the function the warning is not shown anymore, but it is a confusing warning.

Searching the internet yielded the following: https://stackoverflow.com/questions/51719176/r-xlconnect-loadworkbook-warnings-an-illegal-reflective-access-operation-has

It seems XLConnect must be upgraded to Apache POI 4.0.0

**Comment by Frank4Real** [comment]
This is still happening to me. 
RStudio 1.2.5019, R-3.6.1, XLConnect 0.2-15, Windows 10
Anyone know how I can fix this?

**Comment by spoltier** [comment]
Upgraded to 4.1.x in 1.0
