### ISSUE TITLE
cloneSheet doesn't work when sheet contains a chart

### ISSUE THREAD

**Issue by drobertandersson** [miraisolutions/xlconnect#94]
Hi!

I recently started using XLConnect, and it's very useful. 

But I have an issue with the cloneSheet function. When the sheet I try to clone contains a chart (an Excel chart, that is), I can save the Excel file as usual. But when I open the new file in Excel, it gives me the error: 

"We Found A Problem With Some Content In  (file name). Do you want us to try to recover as much as we can?  ... "

When I open the repaired file, the copied sheet exists, but the chart has disappeared, along with all formatting in the file. 

I tested this with the following code:

testbook = loadWorkbook("test file with chart.xlsx")
getSheets(testbook)
cloneSheet(testbook, "sheet with only text", "copy of sheet with only text")
cloneSheet(testbook, "sheet with chart", "copy of sheet with chart")
saveWorkbook(testbook, "test file with chart - modified.xlsx")

[test file with chart.xlsx](https://github.com/miraisolutions/xlconnect/files/3708158/test.file.with.chart.xlsx)

I'm on Windows 10, R 3.6.0, Java v. 8 update 221. 

Is this a known issue, or is it just my system / my file? 

Many thanks in advance!

kind regards,
Robert

**Comment by spoltier** [comment]
Unfortunately, POI support for charts is very [limited](http://poi.apache.org/components/spreadsheet/limitations.html), which means we probably won't be able to implement this if it doesn't work as is.
Possibly this has improved now that we use version 4.1.x of POI.
